### ISSUE TITLE
We should use a front-end modules framework.

### ISSUE THREAD

**Issue by johnttan** [topsoiljs/topsoil#39]
@zindlerb @topsoiljs/owners @asakurasol 

What do you guys think?

**Comment by zindlerb** [comment]
Do you mean something like require.js? I agree that is is kind of annoying to add deps on client side.

**Comment by johnttan** [comment]
Yea, something like require.js. To better organize our dependencies and to modularize some of the common helper functions/modules. We are also running into issues with the stores/views and the order in which they're instantiated.

**Comment by zindlerb** [comment]
Yes! What module system do we want to use?

**Comment by johnttan** [comment]
RequireJS would be fine

**Comment by johnttan** [comment]
#46
